### ISSUE TITLE
the Cube don't follow the Tracker Target

### ISSUE THREAD

**Issue by tyhbj** [VRLabs/Contact-Tracker#14]
After I set it up following the steps in your video，i move the Tracker Target in unity，but the Cube don't follow the Tracker Target，and the ContactTracker's value in Parameters never change.

**Comment by tyhbj** [comment]
In the game, the Cube also does not follow the avatar, but appears directly underground far from the avatar

**Comment by jellejurre** [comment]
if you're on 2019, try updating to the latest version. We accidentally updated the prefab to 2022 which breaks constraints in 2019 which we reverted in the recent update.

Please let us know if this fixes it.

**Comment by tyhbj** [comment]
Yes I did use unity 2019.and for 1.4.7, the Cube does follow Tracker Target in unity,but in parameters, i found ContactTracker/X+ to ContactTracker/Z- 's value don't make any change,they always be 0.

then before i upload the avatar, i make ContactTracker/Control on. but in VRCHAT, the same situation with 1.4.6 shows on,the cube does'nt follow my avatar,and my left hand could'nt interact with cube.

**Comment by jellejurre** [comment]
Can you try it with a toggle for the Control toggle?

Oh and also make sure the Contact Tracker prefab is actually a child of the avatar

And if that doesn't work, can you show a video of the whole install process?

**Comment by tyhbj** [comment]
of course，https://drive.google.com/file/d/1o6nQr5L7J3RBa7l6VZDAiyg0sIQvQkMM/view?usp=sharing

**Comment by jellejurre** [comment]
Your install looks good, it's just missing a few things:

1. You want to put the reset target under your right hand for example, so it moves with the right hand (or whatever transform you want it to move with)
2. You'll need to make a menu item + parameter to toggle the Control bool on for it to work in game
3. It'll only work on other people in game, not on yourself, so I don't know if you were testing alone or not
4. The reason it's not working in your video in the editor is because your GestureManager broken

if you've done all of this and it still doesnt work for you, join [this server](https://discord.vrlabs.dev) and I can help you in vc

**Comment by tyhbj** [comment]
Thanks for the guidance，i drag the target to my hand，now the cube will follow my hand，and when i put it to other’s hand，then i toggle the menu control on，cube stay in the world。 It does not always succeed in tracking other people's hands，and even  when it  succeed in tracking，the cube is so far from their hand。

**Comment by jellejurre** [comment]
Please join the server I sent on discord so I can help you in the vc then

**Comment by tyhbj** [comment]
sorry for getting back to you so late，i joined this discord。
